CREATE TABLE tbl_todos
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title     VARCHAR(255)                            NOT NULL,
    completed BOOLEAN,
    CONSTRAINT pk_tbl_todos PRIMARY KEY (id)
);

ALTER TABLE tbl_todos
    ADD CONSTRAINT uc_tbl_todos_title UNIQUE (title);
CREATE TABLE tbl_todos
(
    id        BIGINT AUTO_INCREMENT NOT NULL,
    title     VARCHAR(255)          NOT NULL,
    completed BIT(1)                NULL,
    CONSTRAINT pk_tbl_todos PRIMARY KEY (id)
);

ALTER TABLE tbl_todos
    ADD CONSTRAINT uc_tbl_todos_title UNIQUE (title);